name: ReinCarnationCore
version: '${version}'
main: siqlet.org.example.reincarnationcore.ReinCarnationCore
api-version: 1.17

commands:
  rctrade:
    aliases: trade
    permission: reincarnation.trade
  sabamin:
    permission: reincarnation.sabamin